### ISSUE TITLE
Could you share the CL4CTR and EulerNet code for your experiments?

### ISSUE THREAD

**Issue by zhujiem** [salmon1802/CETN#2]
Thanks!

**Comment by salmon1802** [comment]
no problems! But you know it's the May Day holiday, maybe I need to send it to you again on the working day. Please send an issue on my GitHub to remind me. Good luck.



---Original---
From: ***@***.***&gt;
Date: Wed, May 1, 2024 17:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [salmon1802/CETN] Could you share the CL4CTR and EulerNet code foryour experiments? (Issue #2)




 
Thanks!

**Comment by salmon1802** [comment]
Thanks for the question, I like the FuxiCTR! :)
I have added the CL4CTR and EulerNet code to this repository.

**Comment by salmon1802** [comment]
> Thanks!
I like the FuxiCTR! :)
I have added the CL4CTR and EulerNet code to this repository.

**Comment by zhujiem** [comment]
Thank you so much for your openning of the code. Would you mind I merge your code to FuxiCTR? I will add your copyright.

**Comment by salmon1802** [comment]
> Thank you so much for your openning of the code. Would you mind I merge your code to FuxiCTR? I will add your copyright.

Absolutely! It would be my pleasure.
